services:
  - type: web
    name: personalized-email-sender
    env: node
    plan: free
    buildCommand: npm install && npm run build:frontend && cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SENDGRID_API_KEY
        sync: false
      - key: COMPANY_NAME
        value: AKROGONOS INTERNATIONAL GROUP
      - key: COMPANY_REPLY_TO
        sync: false